// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: order_entry.proto

package com.scsociety.apps.network;

public final class OrderEntryProto {
  private OrderEntryProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}

  public interface OrderOrBuilder extends
  // @@protoc_insertion_point(interface_extends:scsociety.trading.io.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string contract = 1;</code>
     */
    boolean hasContract();

    /**
     * <code>required string contract = 1;</code>
     */
    java.lang.String getContract();

    /**
     * <code>required string contract = 1;</code>
     */
    com.google.protobuf.ByteString getContractBytes();

    /**
     * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
     */
    boolean hasTimeInForce();

    /**
     * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
     */
    com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce getTimeInForce();

    /**
     * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
     */
    boolean hasType();

    /**
     * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
     */
    com.scsociety.apps.network.OrderEntryProto.Order.Type getType();

    /**
     * <code>required int32 qty = 4;</code>
     */
    boolean hasQty();

    /**
     * <code>required int32 qty = 4;</code>
     */
    int getQty();

    /**
     * <code>required string price = 5;</code>
     */
    boolean hasPrice();

    /**
     * <code>required string price = 5;</code>
     */
    java.lang.String getPrice();

    /**
     * <code>required string price = 5;</code>
     */
    com.google.protobuf.ByteString getPriceBytes();

    /**
     * <code>required string account = 6;</code>
     */
    boolean hasAccount();

    /**
     * <code>required string account = 6;</code>
     */
    java.lang.String getAccount();

    /**
     * <code>required string account = 6;</code>
     */
    com.google.protobuf.ByteString getAccountBytes();

    /**
     * <code>required int32 status = 7 [default = 0];</code>
     */
    boolean hasStatus();

    /**
     * <code>required int32 status = 7 [default = 0];</code>
     */
    int getStatus();

    /**
     * <code>optional uint32 filledQty = 8 [default = 0];</code>
     */
    boolean hasFilledQty();

    /**
     * <code>optional uint32 filledQty = 8 [default = 0];</code>
     */
    int getFilledQty();

    /**
     * <code>optional string avg_fill_price = 9;</code>
     */
    boolean hasAvgFillPrice();

    /**
     * <code>optional string avg_fill_price = 9;</code>
     */
    java.lang.String getAvgFillPrice();

    /**
     * <code>optional string avg_fill_price = 9;</code>
     */
    com.google.protobuf.ByteString getAvgFillPriceBytes();

    /**
     * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
     */
    boolean hasCumulativeQty();

    /**
     * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
     */
    int getCumulativeQty();
  }
  /**
   * Protobuf type {@code scsociety.trading.io.Order}
   */
  public static final class Order extends com.google.protobuf.GeneratedMessage implements
  // @@protoc_insertion_point(message_implements:scsociety.trading.io.Order)
      OrderOrBuilder {
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }

    private Order(boolean noInit) {
      this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private static final Order defaultInstance;

    public static Order getDefaultInstance() {
      return defaultInstance;
    }

    public Order getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Order(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              contract_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce value =
                  com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                timeInForce_ = value;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.scsociety.apps.network.OrderEntryProto.Order.Type value =
                  com.scsociety.apps.network.OrderEntryProto.Order.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              qty_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              price_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              account_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              status_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              filledQty_ = input.readUInt32();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              avgFillPrice_ = bs;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              cumulativeQty_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
            .setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.scsociety.apps.network.OrderEntryProto.internal_static_scsociety_trading_io_Order_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.scsociety.apps.network.OrderEntryProto.internal_static_scsociety_trading_io_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(com.scsociety.apps.network.OrderEntryProto.Order.class,
              com.scsociety.apps.network.OrderEntryProto.Order.Builder.class);
    }

    public static com.google.protobuf.Parser<Order> PARSER =
        new com.google.protobuf.AbstractParser<Order>() {
          public Order parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Order(input, extensionRegistry);
          }
        };

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code scsociety.trading.io.Order.TimeInForce}
     */
    public enum TimeInForce implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DAY = 0;</code>
       */
      DAY(0, 0),
      /**
       * <code>GTC = 1;</code>
       */
      GTC(1, 1),
      /**
       * <code>AUC = 2;</code>
       */
      AUC(2, 2), ;

      /**
       * <code>DAY = 0;</code>
       */
      public static final int DAY_VALUE = 0;
      /**
       * <code>GTC = 1;</code>
       */
      public static final int GTC_VALUE = 1;
      /**
       * <code>AUC = 2;</code>
       */
      public static final int AUC_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      public static TimeInForce valueOf(int value) {
        switch (value) {
          case 0:
            return DAY;
          case 1:
            return GTC;
          case 2:
            return AUC;
          default:
            return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TimeInForce> internalGetValueMap() {
        return internalValueMap;
      }

      private static com.google.protobuf.Internal.EnumLiteMap<TimeInForce> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TimeInForce>() {
            public TimeInForce findValueByNumber(int number) {
              return TimeInForce.valueOf(number);
            }
          };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }

      public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
      }

      public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return com.scsociety.apps.network.OrderEntryProto.Order.getDescriptor().getEnumTypes()
            .get(0);
      }

      private static final TimeInForce[] VALUES = values();

      public static TimeInForce valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private TimeInForce(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:scsociety.trading.io.Order.TimeInForce)
    }

    /**
     * Protobuf enum {@code scsociety.trading.io.Order.Type}
     */
    public enum Type implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LMT = 0;</code>
       */
      LMT(0, 0),
      /**
       * <code>STP = 1;</code>
       */
      STP(1, 1), ;

      /**
       * <code>LMT = 0;</code>
       */
      public static final int LMT_VALUE = 0;
      /**
       * <code>STP = 1;</code>
       */
      public static final int STP_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static Type valueOf(int value) {
        switch (value) {
          case 0:
            return LMT;
          case 1:
            return STP;
          default:
            return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type> internalGetValueMap() {
        return internalValueMap;
      }

      private static com.google.protobuf.Internal.EnumLiteMap<Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }

      public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
        return getDescriptor();
      }

      public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
        return com.scsociety.apps.network.OrderEntryProto.Order.getDescriptor().getEnumTypes()
            .get(1);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:scsociety.trading.io.Order.Type)
    }

    private int bitField0_;
    public static final int CONTRACT_FIELD_NUMBER = 1;
    private java.lang.Object contract_;

    /**
     * <code>required string contract = 1;</code>
     */
    public boolean hasContract() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required string contract = 1;</code>
     */
    public java.lang.String getContract() {
      java.lang.Object ref = contract_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contract_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string contract = 1;</code>
     */
    public com.google.protobuf.ByteString getContractBytes() {
      java.lang.Object ref = contract_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        contract_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEINFORCE_FIELD_NUMBER = 2;
    private com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce timeInForce_;

    /**
     * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
     */
    public boolean hasTimeInForce() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
     */
    public com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce getTimeInForce() {
      return timeInForce_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private com.scsociety.apps.network.OrderEntryProto.Order.Type type_;

    /**
     * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
     */
    public com.scsociety.apps.network.OrderEntryProto.Order.Type getType() {
      return type_;
    }

    public static final int QTY_FIELD_NUMBER = 4;
    private int qty_;

    /**
     * <code>required int32 qty = 4;</code>
     */
    public boolean hasQty() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }

    /**
     * <code>required int32 qty = 4;</code>
     */
    public int getQty() {
      return qty_;
    }

    public static final int PRICE_FIELD_NUMBER = 5;
    private java.lang.Object price_;

    /**
     * <code>required string price = 5;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }

    /**
     * <code>required string price = 5;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          price_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string price = 5;</code>
     */
    public com.google.protobuf.ByteString getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_FIELD_NUMBER = 6;
    private java.lang.Object account_;

    /**
     * <code>required string account = 6;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }

    /**
     * <code>required string account = 6;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string account = 6;</code>
     */
    public com.google.protobuf.ByteString getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private int status_;

    /**
     * <code>required int32 status = 7 [default = 0];</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }

    /**
     * <code>required int32 status = 7 [default = 0];</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int FILLEDQTY_FIELD_NUMBER = 8;
    private int filledQty_;

    /**
     * <code>optional uint32 filledQty = 8 [default = 0];</code>
     */
    public boolean hasFilledQty() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }

    /**
     * <code>optional uint32 filledQty = 8 [default = 0];</code>
     */
    public int getFilledQty() {
      return filledQty_;
    }

    public static final int AVG_FILL_PRICE_FIELD_NUMBER = 9;
    private java.lang.Object avgFillPrice_;

    /**
     * <code>optional string avg_fill_price = 9;</code>
     */
    public boolean hasAvgFillPrice() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }

    /**
     * <code>optional string avg_fill_price = 9;</code>
     */
    public java.lang.String getAvgFillPrice() {
      java.lang.Object ref = avgFillPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          avgFillPrice_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string avg_fill_price = 9;</code>
     */
    public com.google.protobuf.ByteString getAvgFillPriceBytes() {
      java.lang.Object ref = avgFillPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        avgFillPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUMULATIVEQTY_FIELD_NUMBER = 10;
    private int cumulativeQty_;

    /**
     * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
     */
    public boolean hasCumulativeQty() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }

    /**
     * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
     */
    public int getCumulativeQty() {
      return cumulativeQty_;
    }

    private void initFields() {
      contract_ = "";
      timeInForce_ = com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce.DAY;
      type_ = com.scsociety.apps.network.OrderEntryProto.Order.Type.LMT;
      qty_ = 0;
      price_ = "";
      account_ = "";
      status_ = 0;
      filledQty_ = 0;
      avgFillPrice_ = "";
      cumulativeQty_ = 0;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      if (!hasContract()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeInForce()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQty()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContractBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, timeInForce_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, qty_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPriceBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAccountBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, status_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, filledQty_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getAvgFillPriceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(10, cumulativeQty_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1)
        return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getContractBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, timeInForce_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream.computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, qty_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(5, getPriceBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, getAccountBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(7, status_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(8, filledQty_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(9, getAvgFillPriceBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream.computeUInt32Size(10, cumulativeQty_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static com.scsociety.apps.network.OrderEntryProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return Builder.create();
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder(com.scsociety.apps.network.OrderEntryProto.Order prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return newBuilder(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code scsociety.trading.io.Order}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:scsociety.trading.io.Order)
        com.scsociety.apps.network.OrderEntryProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.scsociety.apps.network.OrderEntryProto.internal_static_scsociety_trading_io_Order_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.scsociety.apps.network.OrderEntryProto.internal_static_scsociety_trading_io_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.scsociety.apps.network.OrderEntryProto.Order.class,
                com.scsociety.apps.network.OrderEntryProto.Order.Builder.class);
      }

      // Construct using com.scsociety.apps.network.OrderEntryProto.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }

      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        contract_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timeInForce_ = com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce.DAY;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.scsociety.apps.network.OrderEntryProto.Order.Type.LMT;
        bitField0_ = (bitField0_ & ~0x00000004);
        qty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        price_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        filledQty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        avgFillPrice_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        cumulativeQty_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.scsociety.apps.network.OrderEntryProto.internal_static_scsociety_trading_io_Order_descriptor;
      }

      public com.scsociety.apps.network.OrderEntryProto.Order getDefaultInstanceForType() {
        return com.scsociety.apps.network.OrderEntryProto.Order.getDefaultInstance();
      }

      public com.scsociety.apps.network.OrderEntryProto.Order build() {
        com.scsociety.apps.network.OrderEntryProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.scsociety.apps.network.OrderEntryProto.Order buildPartial() {
        com.scsociety.apps.network.OrderEntryProto.Order result =
            new com.scsociety.apps.network.OrderEntryProto.Order(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contract_ = contract_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeInForce_ = timeInForce_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.qty_ = qty_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.filledQty_ = filledQty_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.avgFillPrice_ = avgFillPrice_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.cumulativeQty_ = cumulativeQty_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.scsociety.apps.network.OrderEntryProto.Order) {
          return mergeFrom((com.scsociety.apps.network.OrderEntryProto.Order) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.scsociety.apps.network.OrderEntryProto.Order other) {
        if (other == com.scsociety.apps.network.OrderEntryProto.Order.getDefaultInstance())
          return this;
        if (other.hasContract()) {
          bitField0_ |= 0x00000001;
          contract_ = other.contract_;
          onChanged();
        }
        if (other.hasTimeInForce()) {
          setTimeInForce(other.getTimeInForce());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasQty()) {
          setQty(other.getQty());
        }
        if (other.hasPrice()) {
          bitField0_ |= 0x00000010;
          price_ = other.price_;
          onChanged();
        }
        if (other.hasAccount()) {
          bitField0_ |= 0x00000020;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasFilledQty()) {
          setFilledQty(other.getFilledQty());
        }
        if (other.hasAvgFillPrice()) {
          bitField0_ |= 0x00000100;
          avgFillPrice_ = other.avgFillPrice_;
          onChanged();
        }
        if (other.hasCumulativeQty()) {
          setCumulativeQty(other.getCumulativeQty());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContract()) {

          return false;
        }
        if (!hasTimeInForce()) {

          return false;
        }
        if (!hasType()) {

          return false;
        }
        if (!hasQty()) {

          return false;
        }
        if (!hasPrice()) {

          return false;
        }
        if (!hasAccount()) {

          return false;
        }
        if (!hasStatus()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.scsociety.apps.network.OrderEntryProto.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.scsociety.apps.network.OrderEntryProto.Order) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object contract_ = "";

      /**
       * <code>required string contract = 1;</code>
       */
      public boolean hasContract() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>required string contract = 1;</code>
       */
      public java.lang.String getContract() {
        java.lang.Object ref = contract_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contract_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string contract = 1;</code>
       */
      public com.google.protobuf.ByteString getContractBytes() {
        java.lang.Object ref = contract_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          contract_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string contract = 1;</code>
       */
      public Builder setContract(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        contract_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string contract = 1;</code>
       */
      public Builder clearContract() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contract_ = getDefaultInstance().getContract();
        onChanged();
        return this;
      }

      /**
       * <code>required string contract = 1;</code>
       */
      public Builder setContractBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        contract_ = value;
        onChanged();
        return this;
      }

      private com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce timeInForce_ =
          com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce.DAY;

      /**
       * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
       */
      public boolean hasTimeInForce() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
       */
      public com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce getTimeInForce() {
        return timeInForce_;
      }

      /**
       * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
       */
      public Builder setTimeInForce(
          com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        timeInForce_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required .scsociety.trading.io.Order.TimeInForce timeInForce = 2;</code>
       */
      public Builder clearTimeInForce() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeInForce_ = com.scsociety.apps.network.OrderEntryProto.Order.TimeInForce.DAY;
        onChanged();
        return this;
      }

      private com.scsociety.apps.network.OrderEntryProto.Order.Type type_ =
          com.scsociety.apps.network.OrderEntryProto.Order.Type.LMT;

      /**
       * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /**
       * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
       */
      public com.scsociety.apps.network.OrderEntryProto.Order.Type getType() {
        return type_;
      }

      /**
       * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
       */
      public Builder setType(com.scsociety.apps.network.OrderEntryProto.Order.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required .scsociety.trading.io.Order.Type type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = com.scsociety.apps.network.OrderEntryProto.Order.Type.LMT;
        onChanged();
        return this;
      }

      private int qty_;

      /**
       * <code>required int32 qty = 4;</code>
       */
      public boolean hasQty() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }

      /**
       * <code>required int32 qty = 4;</code>
       */
      public int getQty() {
        return qty_;
      }

      /**
       * <code>required int32 qty = 4;</code>
       */
      public Builder setQty(int value) {
        bitField0_ |= 0x00000008;
        qty_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required int32 qty = 4;</code>
       */
      public Builder clearQty() {
        bitField0_ = (bitField0_ & ~0x00000008);
        qty_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object price_ = "";

      /**
       * <code>required string price = 5;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }

      /**
       * <code>required string price = 5;</code>
       */
      public java.lang.String getPrice() {
        java.lang.Object ref = price_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            price_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string price = 5;</code>
       */
      public com.google.protobuf.ByteString getPriceBytes() {
        java.lang.Object ref = price_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          price_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string price = 5;</code>
       */
      public Builder setPrice(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        price_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string price = 5;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }

      /**
       * <code>required string price = 5;</code>
       */
      public Builder setPriceBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        price_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";

      /**
       * <code>required string account = 6;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }

      /**
       * <code>required string account = 6;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string account = 6;</code>
       */
      public com.google.protobuf.ByteString getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string account = 6;</code>
       */
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        account_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string account = 6;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }

      /**
       * <code>required string account = 6;</code>
       */
      public Builder setAccountBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        account_ = value;
        onChanged();
        return this;
      }

      private int status_;

      /**
       * <code>required int32 status = 7 [default = 0];</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }

      /**
       * <code>required int32 status = 7 [default = 0];</code>
       */
      public int getStatus() {
        return status_;
      }

      /**
       * <code>required int32 status = 7 [default = 0];</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000040;
        status_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required int32 status = 7 [default = 0];</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = 0;
        onChanged();
        return this;
      }

      private int filledQty_;

      /**
       * <code>optional uint32 filledQty = 8 [default = 0];</code>
       */
      public boolean hasFilledQty() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }

      /**
       * <code>optional uint32 filledQty = 8 [default = 0];</code>
       */
      public int getFilledQty() {
        return filledQty_;
      }

      /**
       * <code>optional uint32 filledQty = 8 [default = 0];</code>
       */
      public Builder setFilledQty(int value) {
        bitField0_ |= 0x00000080;
        filledQty_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 filledQty = 8 [default = 0];</code>
       */
      public Builder clearFilledQty() {
        bitField0_ = (bitField0_ & ~0x00000080);
        filledQty_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object avgFillPrice_ = "";

      /**
       * <code>optional string avg_fill_price = 9;</code>
       */
      public boolean hasAvgFillPrice() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }

      /**
       * <code>optional string avg_fill_price = 9;</code>
       */
      public java.lang.String getAvgFillPrice() {
        java.lang.Object ref = avgFillPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            avgFillPrice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string avg_fill_price = 9;</code>
       */
      public com.google.protobuf.ByteString getAvgFillPriceBytes() {
        java.lang.Object ref = avgFillPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          avgFillPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string avg_fill_price = 9;</code>
       */
      public Builder setAvgFillPrice(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        avgFillPrice_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string avg_fill_price = 9;</code>
       */
      public Builder clearAvgFillPrice() {
        bitField0_ = (bitField0_ & ~0x00000100);
        avgFillPrice_ = getDefaultInstance().getAvgFillPrice();
        onChanged();
        return this;
      }

      /**
       * <code>optional string avg_fill_price = 9;</code>
       */
      public Builder setAvgFillPriceBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        avgFillPrice_ = value;
        onChanged();
        return this;
      }

      private int cumulativeQty_;

      /**
       * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
       */
      public boolean hasCumulativeQty() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }

      /**
       * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
       */
      public int getCumulativeQty() {
        return cumulativeQty_;
      }

      /**
       * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
       */
      public Builder setCumulativeQty(int value) {
        bitField0_ |= 0x00000200;
        cumulativeQty_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional uint32 cumulativeQty = 10 [default = 0];</code>
       */
      public Builder clearCumulativeQty() {
        bitField0_ = (bitField0_ & ~0x00000200);
        cumulativeQty_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:scsociety.trading.io.Order)
    }

    static {
      defaultInstance = new Order(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:scsociety.trading.io.Order)
  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_scsociety_trading_io_Order_descriptor;
  private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_scsociety_trading_io_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData =
        {
            "\n\021order_entry.proto\022\024scsociety.trading.i"
                + "o\"\323\002\n\005Order\022\020\n\010contract\030\001 \002(\t\022<\n\013timeInF"
                + "orce\030\002 \002(\0162\'.scsociety.trading.io.Order."
                + "TimeInForce\022.\n\004type\030\003 \002(\0162 .scsociety.tr"
                + "ading.io.Order.Type\022\013\n\003qty\030\004 \002(\005\022\r\n\005pric"
                + "e\030\005 \002(\t\022\017\n\007account\030\006 \002(\t\022\021\n\006status\030\007 \002(\005"
                + ":\0010\022\024\n\tfilledQty\030\010 \001(\r:\0010\022\026\n\016avg_fill_pr"
                + "ice\030\t \001(\t\022\030\n\rcumulativeQty\030\n \001(\r:\0010\"(\n\013T"
                + "imeInForce\022\007\n\003DAY\020\000\022\007\n\003GTC\020\001\022\007\n\003AUC\020\002\"\030\n"
                + "\004Type\022\007\n\003LMT\020\000\022\007\n\003STP\020\001B-\n\032com.scsociety",
            ".apps.networkB\017OrderEntryProto"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_scsociety_trading_io_Order_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_scsociety_trading_io_Order_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_scsociety_trading_io_Order_descriptor, new java.lang.String[] {
                "Contract", "TimeInForce", "Type", "Qty", "Price", "Account", "Status",
                "FilledQty", "AvgFillPrice", "CumulativeQty",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
